name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Setup Yarn 4
        run: yarn set version stable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Generate .env
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_REGION_CODE: eu-west-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

          EXPRESS_B2_APP_KEY_ID: ${{ secrets.EXPRESS_B2_APP_KEY_ID }}
          EXPRESS_B2_APP_KEY: ${{ secrets.EXPRESS_B2_APP_KEY }}
          EXPRESS_B2_BUCKET_ID: ${{ secrets.EXPRESS_B2_BUCKET_ID }}
          EXPRESS_B2_BUCKET_NAME: ${{ secrets.EXPRESS_B2_BUCKET_NAME }}

          EXPRESS_COGNITO_CLIENT_ID: ${{ secrets.EXPRESS_COGNITO_CLIENT_ID }}
          EXPRESS_DROPBOX_CLIENT_ID: ${{ secrets.EXPRESS_DROPBOX_CLIENT_ID }}
          EXPRESS_STRIPE_SECRET_KEY: ${{ secrets.EXPRESS_STRIPE_SECRET_KEY }}
          EXPRESS_STRIPE_WEBHOOK_SECRET: ${{ secrets.EXPRESS_STRIPE_WEBHOOK_SECRET }}
          EXPRESS_DROPBOX_CLIENT_SECRET: ${{ secrets.EXPRESS_DROPBOX_CLIENT_SECRET }}
          EXPRESS_JWT_SECRET: ${{ secrets.EXPRESS_JWT_SECRET }}
          EXPRESS_COGNITO_SECRET: ${{ secrets.EXPRESS_COGNITO_SECRET }}
          EXPRESS_COGNITO_USER_POOL_ID: ${{ secrets.EXPRESS_COGNITO_USER_POOL_ID }}
          EXPRESS_S3_APP_BUCKET: ${{ secrets.EXPRESS_S3_APP_BUCKET }}
          EXPRESS_S3_TEMP_BUCKET: ${{ secrets.EXPRESS_S3_TEMP_BUCKET }}

          EXPRESS_PUBLIC_BACKEND_URL: ${{ vars.EXPRESS_PUBLIC_BACKEND_URL }}
          EXPRESS_PUBLIC_FRONTEND_URL: ${{ vars.EXPRESS_PUBLIC_FRONTEND_URL }}
        run: yarn gen:env && yarn gen:serverless:env

      - name: Deploy to Serverless
        run: yarn deploy --stage prod
